# Generated by Django 4.1.7 on 2023-03-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
    ]
