# Generated by Django 4.1.7 on 2023-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Salary',
            field=models.FloatField(null=True),
        ),
    ]
